# .github/workflows/test.yml
name: Test

on: [push, workflow_dispatch]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - run: echo "Hello world"
# Run this inside your container
$ npm install --save-dev mocha chai mocha-junit-reporter
